### PR TITLE
Absolute url handling fix

### PR DESCRIPTION
**Pull request by NSLS**
Tested this on a real project, seems to work fine

### CODE REVIEW

**Comment by taion** [comment]
Wait... what does such a redirect actually do? Can you actually redirect to a different origin this way?

**Comment by NSLS** [comment]
Yes, we can

In our setup we have SSR on every project in the system, and upon the request we check if the user is authenticated, and if not - we throw an exception. 

Then, this exception gets handled by our SSR code, and a 301 redirect is thrown. 

In this scenario an absolute redirect is working fine

**Comment by NSLS** [comment]
This behaviour is needed for us, because we our authentication is handled by an external SSO service, which is located at a different origin

**Comment by NSLS** [comment]
And here is the code responsible for SSR redirects

image

**Comment by taion** [comment]
@NSLS I pushed a quick fix to make this a bit more generic and updated the README a bit. Can you let me know if it still works for you? I'll merge and cut a new release if so.

**Comment by taion** [comment]
It's a little weird to have redirects that wouldn't work on the client side, but I see no reason not to support this.

**Comment by NSLS** [comment]
I've checked the code you've commited and it works as intended.

But is it possible to make those kind of redirects possible on the client side too?

At the moment we can determine the environment and make a window.location assignment on the client side, avoiding the `RedirectException` throws, but maybe it would make sense to include this logic into the core as well?

**Comment by taion** [comment]
Yeah, I think what we'd do is to modify (or add an option to enable) `BrowserProtocol` to do something smarter in https://github.com/4Catalyzer/farce/blob/aab75c6f00cdef6a3fd7bfc5d78a35b5bca0c78d/src/BrowserProtocol.js#L48-L71. The only trick is that this wouldn't support things like `state`, &c.

Let's get this in first, though, as this is strictly the correct thing to do.

**Comment by NSLS** [comment]
Yeah, sure

Should I create another issue inside the `farce` repository for now?

**Comment by taion** [comment]
That would be great, thanks!

**Comment by taion** [comment]
released in v0.1.1

**Pull request merged**
